[no-cd]
@_preview FILE:
	nvim --cmd 'set noswapfile | set autoread | au CursorHold * checktime | call feedkeys("lh" )' {{FILE}} 

@view SOURCE="../examples/python/basic_declarative_macro.py" OUTPUT="throw.py":
	zellij action new-tab -n="live preview"
	zellij run -n="watcher" -d=right -- just _preview {{OUTPUT}}	
	zellij action move-focus left
	zellij run -n="editor" -d=up -- hx {{SOURCE}}
	zellij action move-focus up
	zellij action close-pane
	zellij run -n="reloader" -d=down -- watchexec -w {{SOURCE}} -- "./prog > {{OUTPUT}}"
	zellij action move-focus up

	
